apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fg7v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hnvd-tenant/rhtap-demo-app/hacbs-test-project-fg7v@sha256:a4addfa07ac442ebd09e48b0118254aeece9fda660ec141c3315c4f7620f26b2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
