apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fg7v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fg7v
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fg7v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fg7v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fg7v
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hnvd-tenant/rhtap-demo-app/hacbs-test-project-fg7v@sha256:a4addfa07ac442ebd09e48b0118254aeece9fda660ec141c3315c4f7620f26b2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
